### PR TITLE
Fix #62

### LINKED ISSUE #62: Display all reporters per revision
At the moment the main page ( https://make.wordpress.org/hosting/test-results/ ) shows a total of 6 revisions x 10 reporters each.

This creates an unintentional limit and some hosts aren't listed there almost at all times due to the A-Z sorting.

Sometimes it's easier for hosts to just go on the page and see their latests checks if passed/failed from the page than via going on their server.

I'd propose to make a small adjustment if possible and instead of having 6 Revs x 10 hosts, have let's say 3 Revs x All Hosts ( just to avoid getting the page too long to scroll if that would be an issue ).

Ref discussion on hosting-community Slack: https://wordpress.slack.com/archives/C3D6T7F8Q/p1579684779050800

### PR DESCRIPTION
**Pull request by pfefferle**
* show reports of all hosters (no limitations)
* limit the result of revisions (from 5 to 3) in favor of a complete list of host-tests

fix #62

### CODE REVIEW

**Comment by getsource** [comment]
Thanks for the PR!

I like trading off the amount of revisions listed for reporters.

Am thinking we should still have some limit on reporters to avoid having a limitless query. Maybe we can pick something arbitrarily larger that should still work, but might be a good time to re-evaluate how they are retrieved?

**Comment by pfefferle** [comment]
Good point! I changed the code, so that it displays 15 items on the main page and all items on the "single revision" page. We could also try to sort them by "errors first", but perhaps in a separate merge request.

**Comment by getsource** [comment]
Ah, I like that direction.
I had been thinking setting both to something ridiculous like 100(+), so that everyone gets listed, but things are protected from edge cases.

On the latter note, a couple of thoughts:
- Might work to have a limited (maybe randomized?) number (ideally with errors on top), then "click to view all" or something like that. This could probably be done without a redesign.
- Farther, but redesign territory: List only the revision and details, with number of responded + how many errors in `test-results` (with no individual results at all in the table), then show all host results (with some very high limit to avoid edge cases) when clicking through. This option would make it clear what particular revision(s) might have broken/fixed things.

**Comment by getsource** [comment]
Sorry this has taken so long! Wanted to be sure to update:
@aaroncampbell offered to see if we can get some test data so as to be able to test more easily. If that's possible -- awesome! If not, I'll still go ahead with making a mocked set of test users + results.

**Comment by getsource** [comment]
Thanks much!

**Comment by getsource** [comment]
Thanks much!

Wanted to make sure to props @dd32 and @aaroncampbell for test content from make. Thank you!

**Pull request merged**
